package vn.edu.poly.tuanltph04663.model;
// Generated Oct 21, 2017 1:18:00 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private int accountIdAccount;
	private Account account;
	private Set details = new HashSet(0);

	public Cart() {
	}

	public Cart(int accountIdAccount, Account account) {
		this.accountIdAccount = accountIdAccount;
		this.account = account;
	}

	public Cart(int accountIdAccount, Account account, Set details) {
		this.accountIdAccount = accountIdAccount;
		this.account = account;
		this.details = details;
	}

	public int getAccountIdAccount() {
		return this.accountIdAccount;
	}

	public void setAccountIdAccount(int accountIdAccount) {
		this.accountIdAccount = accountIdAccount;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Set getDetails() {
		return this.details;
	}

	public void setDetails(Set details) {
		this.details = details;
	}

}
