package vn.edu.poly.tuanltph04663.model;
// Generated Oct 21, 2017 1:18:00 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private Integer idProducts;
	private Category category;
	private String image;
	private String nameProduct;
	private float price;
	private Set details = new HashSet(0);

	public Products() {
	}

	public Products(Category category, String image, String nameProduct, float price) {
		this.category = category;
		this.image = image;
		this.nameProduct = nameProduct;
		this.price = price;
	}
	
	public Products( String image, String nameProduct, float price) {
		
		this.image = image;
		this.nameProduct = nameProduct;
		this.price = price;
	}


	public Products(Category category, String image, String nameProduct, float price, Set details) {
		this.category = category;
		this.image = image;
		this.nameProduct = nameProduct;
		this.price = price;
		this.details = details;
	}

	public Integer getIdProducts() {
		return this.idProducts;
	}

	public void setIdProducts(Integer idProducts) {
		this.idProducts = idProducts;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getNameProduct() {
		return this.nameProduct;
	}

	public void setNameProduct(String nameProduct) {
		this.nameProduct = nameProduct;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public Set getDetails() {
		return this.details;
	}

	public void setDetails(Set details) {
		this.details = details;
	}

}
